#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define RENDER_DISTANCE_BACK 550.0f
#define RENDER_DISTANCE_FRONT 550.0f

#define RENDER_DISTANCE_BACK_FOR_TREES 600.0f
#define RENDER_DISTANCE_FRONT_FOR_TREES 600.0f

#define FPS 60

#define SPEED_LIMIT 5.1f
#define ACCELERATION 0.005f

#define REVERSE_SPEED_LIMIT -5.1f
#define DECELERATION 0.005f

#define BREAK_POWER 0.01f

#define INTERVALS_FOR_STOPS 2